### ISSUE TITLE
Incorrect number of stamps by countries and categories when collection contains incomplete series

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#1143]
**Steps to reproduce:**
- add a series id=2 to user's collection with only 1 stamp
- on the collection page, check statistics by categories/countries

**Expected result:** 1 stamp
**Actual result:** 2 stamps

**Comment by php-coder** [comment]
This is hard or nearly impossible to test as this statistic affects only diagrams. I'm going to write tests for DAO layer to ensure that the methods returns different numbers depending on data.

**Comment by 0pdd** [comment]
@php-coder 2 puzzles [#1150](https://github.com/php-coder/mystamps/issues/1150), [#1151](https://github.com/php-coder/mystamps/issues/1151) are still not solved.

**Comment by php-coder** [comment]
Done -- both counter have been fixed.

**Comment by 0pdd** [comment]
@php-coder the puzzle [#1151](https://github.com/php-coder/mystamps/issues/1151) is still not solved; solved: [#1150](https://github.com/php-coder/mystamps/issues/1150).
