### ISSUE TITLE
Import series: add support for extracting seller info and price

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#695]
Tech debt for 29f6dc9a14606bc03a63818c59d4bbc62a18499b (#660)

**Comment by php-coder** [comment]
Done.

**Comment by 0pdd** [comment]
@php-coder the puzzle [#863](https://github.com/php-coder/mystamps/issues/863) is still not solved.

**Comment by 0pdd** [comment]
@php-coder the puzzle [#864](https://github.com/php-coder/mystamps/issues/864) is still not solved.

**Comment by 0pdd** [comment]
@php-coder the puzzle [#865](https://github.com/php-coder/mystamps/issues/865) is still not solved.

**Comment by 0pdd** [comment]
@php-coder the puzzle [#866](https://github.com/php-coder/mystamps/issues/866) is still not solved.

**Comment by 0pdd** [comment]
@php-coder the puzzle [#867](https://github.com/php-coder/mystamps/issues/867) is still not solved.

**Comment by 0pdd** [comment]
@php-coder 19 puzzles [#839](https://github.com/php-coder/mystamps/issues/839), [#841](https://github.com/php-coder/mystamps/issues/841), [#842](https://github.com/php-coder/mystamps/issues/842), [#846](https://github.com/php-coder/mystamps/issues/846), [#847](https://github.com/php-coder/mystamps/issues/847), [#849](https://github.com/php-coder/mystamps/issues/849), [#851](https://github.com/php-coder/mystamps/issues/851), [#852](https://github.com/php-coder/mystamps/issues/852), [#853](https://github.com/php-coder/mystamps/issues/853), [#854](https://github.com/php-coder/mystamps/issues/854), [#855](https://github.com/php-coder/mystamps/issues/855), [#856](https://github.com/php-coder/mystamps/issues/856), [#859](https://github.com/php-coder/mystamps/issues/859), [#861](https://github.com/php-coder/mystamps/issues/861), [#863](https://github.com/php-coder/mystamps/issues/863), [#865](https://github.com/php-coder/mystamps/issues/865), [#866](https://github.com/php-coder/mystamps/issues/866), [#867](https://github.com/php-coder/mystamps/issues/867), [#unknown]() are still not solved; solved: [#833](https://github.com/php-coder/mystamps/issues/833), [#834](https://github.com/php-coder/mystamps/issues/834), [#835](https://github.com/php-coder/mystamps/issues/835), [#836](https://github.com/php-coder/mystamps/issues/836), [#838](https://github.com/php-coder/mystamps/issues/838), [#840](https://github.com/php-coder/mystamps/issues/840), [#843](https://github.com/php-coder/mystamps/issues/843), [#844](https://github.com/php-coder/mystamps/issues/844), [#848](https://github.com/php-coder/mystamps/issues/848), [#860](https://github.com/php-coder/mystamps/issues/860), [#864](https://github.com/php-coder/mystamps/issues/864).

**Comment by 0pdd** [comment]
@php-coder 18 puzzles [#839](https://github.com/php-coder/mystamps/issues/839), [#841](https://github.com/php-coder/mystamps/issues/841), [#846](https://github.com/php-coder/mystamps/issues/846), [#847](https://github.com/php-coder/mystamps/issues/847), [#849](https://github.com/php-coder/mystamps/issues/849), [#851](https://github.com/php-coder/mystamps/issues/851), [#852](https://github.com/php-coder/mystamps/issues/852), [#853](https://github.com/php-coder/mystamps/issues/853), [#854](https://github.com/php-coder/mystamps/issues/854), [#855](https://github.com/php-coder/mystamps/issues/855), [#856](https://github.com/php-coder/mystamps/issues/856), [#859](https://github.com/php-coder/mystamps/issues/859), [#861](https://github.com/php-coder/mystamps/issues/861), [#863](https://github.com/php-coder/mystamps/issues/863), [#865](https://github.com/php-coder/mystamps/issues/865), [#866](https://github.com/php-coder/mystamps/issues/866), [#867](https://github.com/php-coder/mystamps/issues/867), [#unknown]() are still not solved; solved: [#833](https://github.com/php-coder/mystamps/issues/833), [#834](https://github.com/php-coder/mystamps/issues/834), [#835](https://github.com/php-coder/mystamps/issues/835), [#836](https://github.com/php-coder/mystamps/issues/836), [#838](https://github.com/php-coder/mystamps/issues/838), [#840](https://github.com/php-coder/mystamps/issues/840), [#842](https://github.com/php-coder/mystamps/issues/842), [#843](https://github.com/php-coder/mystamps/issues/843), [#844](https://github.com/php-coder/mystamps/issues/844), [#848](https://github.com/php-coder/mystamps/issues/848), [#860](https://github.com/php-coder/mystamps/issues/860), [#864](https://github.com/php-coder/mystamps/issues/864).
